### ISSUE TITLE
Question : add toc in your example ?

### ISSUE THREAD

**Issue by ddotta** [tvroylandt/sgdf_pagedown#1]
Hello Thomas
Very nice job! Very inspiring.
I really need to take some time to read the documentation...
In your example, how would you add a table of contents?
Thank's in advance !
Damien

**Comment by tvroylandt** [comment]
Hello Damien,

Thanks. Just add a `toc:true` in the YAML header.
The TOC will not be formatted because i didn't care here about it. But if you want to see a formatted TOC for `pagedown`, see https://github.com/rfortherestofus/omni/blob/7b9666f40472b668a0fd624e49ab2fa6776364b0/inst/rmarkdown/templates/omni-rmarkdown-template/skeleton/css/omni-page.css#L204 (pay attention to the license if you want to re-use it).

**Comment by ddotta** [comment]
Thank you very much for this information!
I'm going to try to personalize my toc, not sure I'll be able to do it, but it doesn't try anything...
